[build]
command = "echo 'skip build - already exported'" # Netlify의 자동 build 무시
publish = "functions/out"                         # export 결과물 위치

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200